# React
# integ_react_storage
- test_name: 'React Storage'
  framework: react
  category: storage
  sample_name: storageApp
  spec: storage
  browser: minimal_browser_list

# integ_react_storage_multipart_progress
- test_name: 'React Storage Multi-Part Upload with Progress'
  framework: react
  category: storage
  sample_name: multi-part-upload-with-progress
  spec: multi-part-upload-with-progress
  browser: minimal_browser_list

# integ_react_storage_copy
- test_name: 'React Storage Copy'
  framework: react
  category: storage
  sample_name: multi-part-copy-with-progress
  spec: multi-part-copy-with-progress
  browser: minimal_browser_list
