# # React
# # integ_react_datastore
# - test_name: 'React DataStore'
#   framework: react
#   category: datastore
#   sample_name: many-to-many
#   spec: many-to-many
#   browser: minimal_browser_list

# # integ_react_datastore_v2
# - test_name: 'React DataStore CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/many-to-many-v2
#   spec: many-to-many
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_one_rule
# - test_name: 'React DataStore Multi-Auth - One Rule'
#   framework: react
#   category: datastore
#   sample_name: multi-auth
#   spec: multi-auth-one-rule
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_one_rule_v2
# - test_name: 'React DataStore Multi-Auth - One Rule CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/multi-auth-v2
#   spec: multi-auth-one-rule
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_two_rules
# - test_name: 'React DataStore Multi-Auth - Two Rules'
#   framework: react
#   category: datastore
#   sample_name: multi-auth
#   spec: multi-auth-two-rules
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_two_rules_v2
# - test_name: 'React DataStore Multi-Auth - Two Rules CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/multi-auth-v2
#   spec: multi-auth-two-rules
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_three_plus_rules
# - test_name: 'React DataStore Multi-Auth - Three Plus Rules'
#   framework: react
#   category: datastore
#   sample_name: multi-auth
#   spec: multi-auth-three-plus-rules
#   browser: minimal_browser_list

# # integ_react_datastore_multi_auth_three_plus_rules_v2
# - test_name: 'React DataStore Multi-Auth - Three Plus Rules CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/multi-auth-v2
#   spec: multi-auth-three-plus-rules
#   browser: minimal_browser_list

# # integ_react_datastore_subs_disabled
# - test_name: 'DataStore - Subs Disabled'
#   framework: react
#   category: datastore
#   sample_name: subs-disabled
#   spec: subs-disabled
#   browser: minimal_browser_list

# # integ_react_datastore_subs_disabled_v2
# - test_name: 'DataStore - Subs Disabled CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/subs-disabled-v2
#   spec: subs-disabled
#   browser: minimal_browser_list

# # integ_react_datastore_consecutive_saves
# - test_name: 'DataStore - Subs Disabled'
#   framework: react
#   category: datastore
#   sample_name: consecutive-saves
#   spec: consecutive-saves
#   browser: minimal_browser_list

# # integ_react_datastore_consecutive_saves_v2
# - test_name: 'DataStore - Subs Disabled CLI v2'
#   framework: react
#   category: datastore
#   sample_name: v2/consecutive-saves-v2
#   spec: consecutive-saves
#   browser: minimal_browser_list

# # # integ_react_datastore_observe_query
# # - test_name: 'DataStore - Observe Query'
# #   framework: react
# #   category: datastore
# #   sample_name: observe-query
# #   spec: observe-query
# #   browser: minimal_browser_list

# # # integ_react_datastore_observe_query_v2
# # - test_name: 'DataStore - Observe Query CLI v2'
# #   framework: react
# #   category: datastore
# #   sample_name: v2/observe-query-v2
# #   spec: observe-query
# #   browser: minimal_browser_list

# # integ_react_datastore_schema_drift
# - test_name: 'DataStore - Schema Drift'
#   framework: react
#   category: datastore
#   sample_name: schema-drift
#   spec: schema-drift
#   browser: minimal_browser_list

# # integ_datastore_auth
# - test_name: 'DataStore Auth - Chrome'
#   framework: react
#   category: datastore
#   sample_name: datastore_auth_scenarios_sample_spec
#   spec: ''
#   browser: chrome    
# - test_name: 'DataStore Auth - Firefox'
#   framework: react
#   category: datastore
#   sample_name: datastore_auth_scenarios_sample_spec
#   spec: ''
#   browser: firefox

# integ_datastore_auth_v2
- test_name: 'DataStore Auth CLI v2 - Chrome'
  framework: react
  category: datastore
  sample_name: datastore_auth_scenarios_sample_spec_v2
  spec: ''
  browser: chrome
- test_name: 'DataStore Auth CLI v2 - Firefox'
  framework: react
  category: datastore
  sample_name: datastore_auth_scenarios_sample_spec_v2
  spec: ''
  browser: firefox

# # integ_react_datastore_custom_pk_unconnected_models
# - test_name: 'DataStore - Custom Primary Key (Connected Models)'
#   framework: react
#   category: datastore
#   sample_name: v2/custom-pk-unconnected-models
#   spec: custom-pk-unconnected-models
#   browser: extended_browser_list

# # integ_react_datastore_custom_pk_unconnected_models_webkit
# - test_name: 'DataStore - Custom Primary Key (Connected Models)'
#   framework: react
#   category: datastore
#   sample_name: v2/custom-pk-unconnected-models
#   spec: custom-pk-unconnected-models
#   browser: webkit

# # integ_react_datastore_custom_pk_has_one
# - test_name: 'DataStore - Custom Primary Key (Has One)'
#   framework: react
#   category: datastore
#   sample_name: v2/custom-pk-has-one
#   spec: custom-pk-has-one
#   browser: minimal_browser_list

# # integ_react_datastore_custom_pk_has_many_many_to_many
# - test_name: 'DataStore - Custom Primary Key (Has Many / Many to Many)'
#   framework: react
#   category: datastore
#   sample_name: v2/custom-pk-has-many-many-to-many
#   spec: custom-pk-has-many-many-to-many
#   browser: minimal_browser_list

# # integ_react_datastore_background_process_manager
# - test_name: 'DataStore - Background Process Manager'
#   framework: react
#   category: datastore
#   sample_name: v2/background-process-manager
#   spec: background-process-manager
#   browser: extended_browser_list

# # integ_react_datastore_background_process_manager_webkit
# - test_name: 'DataStore - Background Process Manager'
#   framework: react
#   category: datastore
#   sample_name: v2/background-process-manager
#   spec: background-process-manager
#   browser: webkit

# # integ_react_datastore_related_models
# - test_name: 'DataStore - Related Models'
#   framework: react
#   category: datastore
#   sample_name: related-models
#   spec: related-models
#   browser: minimal_browser_list

# # integ_react_datastore_selective_sync
# - test_name: 'DataStore - Selective Sync'
#   framework: react
#   category: datastore
#   sample_name: selective-sync-v5
#   spec: selective-sync-v5
#   browser: minimal_browser_list

# # integ_react_datastore_nested_predicate
# - test_name: 'DataStore - Nested Predicate'
#   framework: react
#   category: datastore
#   sample_name: nested-predicate
#   spec: nested-predicate
#   browser: minimal_browser_list

# # integ_react_datastore_docs_examples
# - test_name: 'DataStore - Docs Examples'
#   framework: react
#   category: datastore
#   sample_name: v2/amplify-docs-examples
#   spec: amplify-docs-examples
#   browser: minimal_browser_list

# # integ_react_datastore_websocket_disruption
# - test_name: 'DataStore - WebSocket Disruption'
#   framework: react
#   category: datastore
#   sample_name: websocket-disruption
#   spec: websocket-disruption
#   browser: << parameters.browser >>

# # Javascript
# # integ_vanilla_js_datastore_basic_crud
# - test_name: 'Vanilla JS + Webpack 4 + DataStore - Basic CRUD'
#   framework: javascript
#   category: datastore
#   sample_name: basic-crud
#   browser: minimal_browser_list
#   spec: vanilla-js-basic-crud
#   amplifyjs_dir: true

# # Next
# # integ_next_datastore_owner_auth
# - test_name: 'next owner auth'
#   framework: next
#   category: datastore
#   sample_name: owner-based-default
#   spec: next-owner-based-default
#   browser: minimal_browser_list

# # integ_next_datastore_13_basic
# - test_name: 'DataStore - Nextjs 13 build with SWC - basic JS app'
#   framework: next
#   category: datastore
#   sample_name: next-13-basic
#   spec: nextjs-13-basic
#   browser: minimal_browser_list

# # integ_next_datastore_13_js
# - test_name: 'DataStore - Nextjs 13 build with SWC - JS app'
#   framework: next
#   category: datastore
#   sample_name: next-13-js
#   spec: nextjs-13
#   browser: minimal_browser_list

# # Vite
# # integ_vite_datastore_basic_crud
# - test_name: 'Vite + DataStore - Basic CRUD'
#   framework: vite
#   category: datastore
#   sample_name: v2/basic-crud
#   spec: vite-basic-crud

# # Rollup
# # integ_rollup_datastore_basic_crud
# - test_name: 'Rollup + DataStore - Basic CRUD'
#   framework: rollup
#   category: datastore
#   sample_name: rollup-basic-crud
#   spec: rollup-basic-crud
