# React
# integ_react_iot_reconnect
- test_name: 'PubSub - Reconnection for IoT'
  framework: react
  category: pubsub
  sample_name: reconnection-iot
  spec: reconnection
  # Firefox doesn't support network state management in cypress
  browser: chrome

# integ_react_api_reconnect
- test_name: 'PubSub - Reconnection for API'
  framework: react
  category: pubsub
  sample_name: reconnection-api
  spec: reconnection
  # Firefox doesn't support network state management in cypress
  browser: chrome

