minimal_browser_list:
  - chrome
  - firefox

extended_browser_list:
  - chrome
  - firefox
  - edge

datastore_auth_scenarios_sample_spec:
  - owner-based-default owner-based-default # TODO: Add `owner-based-operations` when tests pass
  - static-user-pool-groups-default static-user-pool-groups-default
  - static-user-pool-groups-operations static-user-pool-groups-operations
  - owner-and-group-different-models-default owner-and-group-different-models-default
  - owner-and-group-same-model-default owner-and-group-same-model-default
  - owner-and-group-same-model-operations owner-and-group-same-model-operations
  - dynamic-user-pool-groups-default dynamic-user-pool-groups-default
  - dynamic-user-pool-groups-owner-based-default dynamic-user-pool-groups-owner-based-default
  - private-auth-default private-auth-default
  - private-auth-iam private-auth-iam
  - public-auth-default public-auth-default
  - public-auth-iam public-auth-iam
  - owner-custom-claim-default owner-custom-claim-default
  - owner-custom-field-default owner-custom-field-default
