name: Publish to NPM
description: Publish changes from

inputs:
  target:
    description: The release process target (either release or preid)
    required: true
  preid:
    description: The preid to release to when the target is preid. The preid process will fail if this isn't provided.
    required: false
  github_email:
    description: The github user email to use to make commits
    required: true
  github_name:
    description: The github user email to use to make commits
    required: true
  bash_env:
    description: The bash_env filename to use to construct and execute PREID content from
    required: false
    default: .env
  npm_token:
    description: The npm token the gives the job npm permissions
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run npm publish
      working-directory: ./amplify-js
      shell: bash
      run: |
        echo "a"
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_token }}" >> ~/.npmrc
        echo "b"
        touch {{ inputs.bash_env }}
        echo "c"
        echo "export PREID_HASH_SUFFIX=$(echo ${{ github.sha }} | cut -c -7 | sed 's/^/\./')" >> "{{ inputs.bash_env }}"
        echo "d"
        echo "export PREID_PREFIX=${{ inputs.preid || '' }}" >> "{{ inputs.bash_env }}"
        echo "e"
        source "{{ inputs.bash_env }}"
        echo "f"
        git config --global user.email {{ inputs.github_email }}
        echo "g"
        git config --global user.name {{ inputs.github_name }}
        echo "h"
        git status
        git --no-pager diff
        yarn publish:${{ inputs.target }}
