name: 'Log Metric'
description: 'Log data point to a metric with the provided value. If the metric is not there, it will create one.'
inputs:
  metric-name:
    description: 'target metric name'
    required: true
  value:
    description: 'the value to log to the metric'
    required: true
  role-to-assume:
    description: 'target AWS account IAM role to assume'
    required: true
  aws-region:
    description: 'target AWS account region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0 https://github.com/aws-actions/configure-aws-credentials/commit/e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
    - name: Put metric data
      shell: bash
      # Run bash script to put metric data.
      # First trim the input by removing trailing or leading spaces, then removing any new line characters.
      # Then, we do regex test to match against expected input shape. Finally, put metric data using aws cli.
      run: |
        metric_name_trimmed="$(echo -e "${metric_name}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tr -d '\n')"
        value_trimmed="$(echo -e "${value}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | tr -d '\n')"

        if ! [[ "$metric_name_trimmed" =~ ^[a-zA-Z0-9\ \_\-]+$ ]]; then
          echo "Metric name can only contain alphanumeric characters, space character, -, and _."
          exit 1
        fi

        if ! [[ "$value_trimmed" =~ ^[-+]?[0-9]+\.?[0-9]*$ ]]; then
          echo "Metric value must be a valid number"
          exit 1
        fi

        aws cloudwatch put-metric-data --metric-name "$metric_name" --namespace AmplifyJsCanaries --value "$value"
      env:
        metric_name: ${{ inputs.metric-name }}
        value: ${{ inputs.value }}