name: Validate changes to "aws-amplify" package.json file
on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
jobs:
  checkUmbrellaDependencies:
    permissions:
      pull-requests: write # Used to add comment to PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Determine if "aws-amplify" package.json has been changed
        id: aws-amplify-package-check
        uses: tj-actions/changed-files@v36
        with:
          files: packages/aws-amplify/package.json
      - name: Write a PR comment
        uses: actions/github-script@v6
        if: steps.aws-amplify-package-check.outputs.any_changed == 'true'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ This PR includes manual changes to the "aws-amplify" package.json file, which can have library-wide implications. 

              Please ensure that this PR:
              - Does not modify "@aws-amplify/*" dependency versions, which may misalign core dependencies across the library.
              
              A repository administrator **is required** to review & merge this change.`
            })
      - name: Fail status check
        if: steps.aws-amplify-package-check.outputs.any_changed == 'true'
        run: exit 1
