name: 'E2E Tests'

on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
      framework:
        required: true
        type: string
      category:
        required: true
        type: string
      sample_name:
        required: true
        type: string
      spec:
        required: false
        type: string
        default: ''
      browser:
        required: false
        type: string
        default: ''
      amplifyjs_dir:
        required: false
        type: boolean
        default: false
      additional_params:
        required: false
        type: string
        default: ''

env:
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js
  AMPLIFY_DIR: /home/runner/work/amplify-js/amplify-js/aws-amplify
jobs:
  # mock-job:
  #   name: mock the job
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       additional_params: ${{ fromJson(inputs.additional_params) }}
  #   steps:
  #     - name: check result
  #       run: |
  #         echo '${{ matrix.additional_params }}'
  #         echo '${{ matrix.additional_params.sample_name }}'
  #         echo '${{ matrix.additional_params.spec }}'

  e2e-test:
    name: 'E2E: ${{ inputs.test_name }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # browser: ${{ fromJson(inputs.browser) }}
        additional_params: ${{ fromJson(inputs.additional_params) }}
        another_additional_params: ${{ fromJson(inputs.additional_params) }}
      fail-fast: false
    timeout-minutes: 35

    steps:
      - name: check incoming config
        run: |
          echo \
          "${{ inputs.framework }} \
          ${{ inputs.category }} \
          ${{ inputs.sample_name }} \
          ${{ inputs.spec }} \
          ${{ matrix.browser }} \
          ${{ inputs.amplifyjs_dir }}"

          echo '${{ matrix.additional_params }}'
          echo '${{ matrix.additional_params.sample_name }}'
          echo '${{ matrix.additional_params.spec }}'

      # - name: Checkout repository
      #   uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
      #   with:
      #     # Minimal depth 2 so we can checkout the commit before possible merge commit.
      #     fetch-depth: 2
      #     path: aws-amplify
      # - name: Setup node and build the repository
      #   uses: ./aws-amplify/.github/actions/node-and-build
      # - name: Setup samples staging repository
      #   uses: ./aws-amplify/.github/actions/setup-samples-staging
      #   with:
      #     GH_PAT: ${{ secrets.GH_PAT }}
      # - name: Load Verdaccio with AmplifyJs
      #   uses: ./aws-amplify/.github/actions/load-verdaccio-with-amplify-js
      # - name: Run cypress tests for ${{ inputs.test_name }} dev
      #   run: |
      #     ../aws-amplify/.circleci/retry-yarn-script.sh -s \
      #     "ci:test ${{ inputs.framework }} ${{ inputs.category }} ${{ inputs.sample_name }} ${{ matrix.additional_params.sample_name || '' }} ${{ inputs.spec }} ${{ matrix.additional_params.spec || '' }} ${{ matrix.browser }} dev ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}" -n 3
      #   working-directory: amplify-js-samples-staging
      #   shell: bash
      # - name: Run cypress tests for ${{ inputs.test_name }} prod
      #   run: |
      #     ../aws-amplify/.circleci/retry-yarn-script.sh -s \
      #     "ci:test ${{ inputs.framework }} ${{ inputs.category }} ${{ inputs.sample_name }} ${{ matrix.additional_params.sample_name || '' }} ${{ inputs.spec }} ${{ matrix.additional_params.spec || '' }} ${{ matrix.browser }} prod ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}" -n 3
      #   working-directory: amplify-js-samples-staging
      #   shell: bash
