name: 'Unit Tests'

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  unit_test:
    name: Unit Tests - ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - name: Setup node and build the repository
        uses: ./.github/actions/node-and-build
      - name: Run tests
        run: npx lerna exec --scope ${{ inputs.package }} yarn test
