name: Release to npm and update repository

on: workflow_call

permissions:
  contents: write

jobs:
  deploy:
    name: Publish to Amplify Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js

      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build

      - name: FOR TESTING Load Verdaccio with AmplifyJs
        uses: ./amplify-js/.github/actions/load-verdaccio-with-amplify-js

      - name: Run npm publish
        uses: ./amplify-js/.github/actions/npm-publish
        with:
          target: release
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_user: ${{ vars.GH_USER}}
          github_email: ${{ vars.GH_EMAIL}}

      - name: Set github commit user
        env:
          GITHUB_EMAIL: ${{ vars.GH_EMAIL }}
          GITHUB_USER: ${{ vars.GH_USER }}
        run: |
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER

      - name: Update roll-back infrastructure
        working-directory: ./amplify-js
        run: |
          git pull origin release
          PUBLISH_COMMIT_HASH=$(git log -n 1 --pretty=format:"%H")
          RELEASE_COMMIT_MESSAGE=$(git log -n 1 --skip 1 --pretty=oneline)
          if [[ $RELEASE_COMMIT_MESSAGE = *release\(required\)* ]]; then git tag -f required-release $PUBLISH_COMMIT_HASH; fi

      - name: Update API documentation
        working-directory: ./amplify-js
        run: |
          yarn run docs
          git add ./docs/api/
          git commit -m "chore(release): update API docs [ci skip]"

      - name: Push post release changes
        working-directory: ./amplify-js
        run: |
          git push origin release
          git push -f origin required-release

      - name: Create PR back to main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_AUTOMATION }}
        run: |
          gh pr create \
          --title "chore: Merge release back to main" \
          --body "Merge version updates and docs changes from `release` back to `main`." \
          --head release \
          --base main
