name: Release Verification Tests

on: workflow_call

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml