name: Publish package to npm and create release on github

on:
  workflow_call:
    inputs:
      preid:
        required: false
        type: string

# TODO: configure these env variables
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # TODO verdaccio stuff we won't need in prod

jobs:
  deploy:
    name: Publish to Amplify Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
      ###
      # TODO Remove this to enable real NPM interactions.
      # <remove>
      - name: Load Verdaccio with AmplifyJs
        uses: ./amplify-js/.github/actions/load-verdaccio-with-amplify-js
      ### </remove>

      - name: Run npm publish
        uses: ./amplify-js/.github/actions/npm-publish
        with:
          github_email: aws@amazon.com
          github_name: aws-amplify-bot
          target: preid
          preid: ${{ inputs.preid }}
          npm_token: ${{ secrets.NPM_TOKEN }}
