name: 'E2E Tests'

on:
  workflow_call:

jobs:
  prebuild-ubuntu:
    uses: ./amplify-js/.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-macos:
    uses: ./amplify-js/.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./amplify-js/.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./amplify-js/.github/workflows/callable-e2e-runner.yml
  get-package-list:
    uses: ./amplify-js/.github/workflows/callable-get-package-list.yml
  unit-tests:
    needs:
      - prebuild-ubuntu
      - get-package-list
    strategy:
      matrix:
        package: ${{ fromJSON(needs.get-package-list.outputs.packages) }}
      fail-fast: false
    uses: ./amplify-js/.github/workflows/callable-unit-tests.yml
    with:
      package: ${{ matrix.package }}
  bundle-size-tests:
    needs: prebuild-ubuntu
    uses: ./amplify-js/.github/workflows/callable-bundle-size-tests.yml
