name: E2E Tests

on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
      framework:
        required: true
        type: string
      category:
        required: true
        type: string
      sample_name:
        required: true
        type: string
      spec:
        required: false
        type: string
        default: ''
      browser:
        required: false
        type: string
        default: ''
      amplifyjs_dir:
        required: false
        type: boolean
        default: false
      timeout_minutes:
        required: true
        type: number
      retry_count:
        required: true
        type: number

env:
  AMPLIFY_DIR: /home/runner/work/amplify-js/amplify-js/amplify-js
  CYPRESS_GOOGLE_CLIENTID: ${{ secrets.CYPRESS_GOOGLE_CLIENTID }}
  CYPRESS_GOOGLE_CLIENT_SECRET: ${{ secrets.CYPRESS_GOOGLE_CLIENT_SECRET }}
  CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.CYPRESS_GOOGLE_REFRESH_TOKEN }}

jobs:
  e2e-test:
    name: E2E ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - ${{ fromJson(inputs.browser) }}
        sample_name:
          - ${{ fromJson(inputs.sample_name) }}
      fail-fast: false
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}
      - name: Load Verdaccio with AmplifyJs
        uses: ./amplify-js/.github/actions/load-verdaccio-with-amplify-js
      - name: Run cypress tests for ${{ inputs.test_name }} dev
        shell: bash
        working-directory: amplify-js-samples-staging
        env:
          E2E_FRAMEWORK: ${{ inputs.framework }}
          E2E_CATEGORY: ${{ inputs.category }}
          E2E_SAMPLE_NAME: ${{ matrix.sample_name }}
          E2E_SPEC: ${{ inputs.spec }}
          E2E_BROWSER: ${{ matrix.browser }}
          E2E_AMPLIFY_JS_DIR: ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}
          E2E_RETRY_COUNT: ${{ inputs.retry_count }}
          E2E_TEST_NAME: ${{ inputs.test_name }}
        run: |
          ../amplify-js/scripts/retry-yarn-script.sh -s \
          "ci:test \
          $E2E_FRAMEWORK \
          $E2E_CATEGORY \
          $E2E_SAMPLE_NAME \
          $E2E_SPEC \
          $E2E_BROWSER \
          dev \
          $E2E_AMPLIFY_JS_DIR" \
          -n $E2E_RETRY_COUNT

      - name: Run cypress tests for $E2E_TEST_NAME prod
        shell: bash
        working-directory: amplify-js-samples-staging
        env:
          E2E_FRAMEWORK: ${{ inputs.framework }}
          E2E_CATEGORY: ${{ inputs.category }}
          E2E_SAMPLE_NAME: ${{ matrix.sample_name }}
          E2E_SPEC: ${{ inputs.spec }}
          E2E_BROWSER: ${{ matrix.browser }}
          E2E_AMPLIFY_JS_DIR: ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}
          E2E_RETRY_COUNT: ${{ inputs.retry_count }}
          E2E_TEST_NAME: ${{ inputs.test_name }}
        run: |
          ../amplify-js/scripts/retry-yarn-script.sh -s \
          "ci:test \
          $E2E_FRAMEWORK \
          $E2E_CATEGORY \
          $E2E_SAMPLE_NAME \
          $E2E_SPEC \
          $E2E_BROWSER \
          prod \
          $E2E_AMPLIFY_JS_DIR" \
          -n $E2E_RETRY_COUNT
      - name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2 https://github.com/actions/upload-artifact/commit/0b7f8abb1508181956e8e162db84b466c27e18ce
        if: failure()
        with:
          name: e2e-test-artifacts
          if-no-files-found: ignore
          path: |
            amplify-js-samples-staging/cypress/videos
            amplify-js-samples-staging/cypress/screenshots
          retention-days: 14
