name: 'Capture Package Names List to Outputs'

on:
  workflow_call:
    outputs:
      packages:
        description: 'The json encoded package list'
        value: ${{ jobs.get-package-list.outputs.packages }}
jobs:
  get-package-list:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
      - uses: actions/cache@v2
        id: cache-package-list
        with:
          path: |
            **/package-list.json
          key: ${{ runner.os }}-package-list-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-package-list-
      - name: Install
        if: steps.cache-package-list.outputs.cache-hit != 'true'
        run: yarn
        shell: bash
      # Need the repo checked out in order to read the file
      - name: Dump Package List
        if: steps.cache-package-list.outputs.cache-hit != 'true'
        run: |
          echo "packages=$(yarn lerna ls | egrep -v "lerna|Done|yarn" | jq -R -s -c 'split("\n")[:-1]')" > package-list.json
      - name: Get Package List
        id: get_package_list
        run: |
          cat package-list.json >> $GITHUB_OUTPUT
    outputs:
      packages: ${{ steps.get_package_list.outputs.packages }}
