name: 'Prebuild Amplify'

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  prebuild:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js
      - name: Setup node and build the repository
        uses: stocaaro/amplify-js/.github/actions/node-and-build@main
        with:
          is-prebuild: true
