name: 'Canary E2E Tests'

on:
  workflow_call:

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-macos:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-canary-e2e-runner.yml
  sample-app-tests:
    secrets: inherit
    uses: ./.github/workflows/callable-canary-sampleapp-tests.yml

  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js    
  log-failure-metric:
    # Send a failure data point to metric PublishNextFailure in github-workflows@ us-east-2, if it's a failure
    runs-on: ubuntu-latest
    environment: ci
    #needs: build-test
    if: ${{ failure() }}
    steps:
      - name: Log failure data point to metric PublishNextFailure
        uses: ./.github/actions/log-metrics/action.yml
        with:
          metric-name: PublishNextFailure
          value: 1
          role-to-assume: ${{ secrets.METRIC_LOGGER_ROLE_ARN }} #what is this?
          aws-region: us-east-2

  log-success-metric:
      # Send a success data point to metric PublishNextFailure in github-workflows@ us-east-2, if it's a success
      runs-on: ubuntu-latest
      environment: ci
      #needs: build-test
      if: ${{ success() }}
      steps:
        - name: Log success data point to metric PublishNextFailure
          uses: ./.github/actions/log-metrics/action.yml
          with:
            metric-name: PublishNextFailure
            value: 0
            role-to-assume: ${{ secrets.METRIC_LOGGER_ROLE_ARN }} #what is this?
            aws-region: us-east-2
