name: Release Verification Tests

on: workflow_call

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e1:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
  e2e2:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
  e2e3:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
  e2e4:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
  e2e5:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
  e2e6:
    needs:
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests-focus.yml
