name: 'Prebuild AmplifyJs'

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js
      - name: Setup samples staging
        uses: stocaaro/amplify-js/.github/actions/setup-samples-staging@main
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
