name: 'Canary Sample App Tests'

on:
  workflow_call:

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        languages: ['react'] #missing Vue because it's run differently

    steps: 
      - name: Create application
        run: npx create-${{ matrix.languages }}-app ${{ matrix.languages }}-amplified
      - name: Change directory
        run: cd ${{ matrix.languages }}-amplified

      - name: What are my files?
        run: ls

      - name: Run application
        run: npm start

