name: 'Release to preid'

on:
  workflow_call:
    inputs:
      preid:
        required: true
        type: string

jobs:
  release-to-preid:
    uses: ./.github/workflows/callable-npm-publish.yml
    with:
      target: preid
      preid: ${{ inputs.preid }}
