name: 'Canary Sample App Tests'

on:
  workflow_call:

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js  
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}

        #React
      - name: Create application
        run: npx create-react-app react-amplified
      - name: Copy App.js from Samples Staging Repo
        run: |
          cp ./amplify-js-samples-staging/samples/react/auth/credentials-auth/src/App.js ./react-amplified/App.js
      - name: Run application
        run: npm start
        working-directory: react-amplified

