name: 'Publish package to npm and create release on github'

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

# TODO: configure these env variables
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_EMAIL: test@email.com
  GITHUB_USER: test-user
  BASH_ENV: .env

jobs:
  deploy:
    name: 'Publish to Amplify Package'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: aws-amplify
      - name: Setup node and build the repository
        uses: ./aws-amplify/.github/actions/node-and-build
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          touch $BASH_ENV
          echo "export PREID_HASH_SUFFIX=$(echo ${{ github.sha }} | cut -c -7 | sed 's/^/\./')" >> "$BASH_ENV"
          source "$BASH_ENV"
          npm whoami
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER
          git status
          git --no-pager diff
          yarn publish:${{ inputs.branch }}
