name: 'Release to latest'

on:
  workflow_call:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: NPM Publish
        uses: stocaaro/amplify-js/.github/callable-npm-publish@main
        with:
          target: release
