name: 'Canary Sample App Tests'

on:
  workflow_call:

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        languages: ['react', 'javascript'] #missing Next, Vue, Angular because run differently

    steps: 
      - name: Create application
        run: npx create-${{ matrix.languages }}-app ${{ matrix.languages }}-amplified
      - name: Change directory #do I need this?
        run: cd ${{ matrix.languages }}-amplified
      - name: Run application
        run: npm start
        working-directory: ${{ matrix.languages }}-amplified

