name: 'Canary Sample App Tests'

on:
  workflow_call:

env:      
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js
  AMPLIFY_DIR: /home/runner/work/amplify-js/amplify-js/amplify-js
  CYPRESS_GOOGLE_CLIENTID: ${{ secrets.CYPRESS_GOOGLE_CLIENTID }}
  CYPRESS_GOOGLE_CLIENT_SECRET: ${{ secrets.CYPRESS_GOOGLE_CLIENT_SECRET }}
  CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.CYPRESS_GOOGLE_REFRESH_TOKEN }}

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        BROWSER: [chrome]

    steps: 
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js  
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}
      - name: Setup node and build the repository
        uses: stocaaro/amplify-js/.github/actions/node-and-build@main

      #   #React
      # - name: Create react application
      #   run: npx create-react-app react-amplified
      #   working-directory: amplify-js-samples-staging/samples/react/auth
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/react/auth/react-amplified
      # - name: Copy src from samples staging repo
      #   run: |
      #     cp -R ./samples/react/auth/credentials-auth/src ./samples/react/auth/react-amplified
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp credentials-auth.spec.js react-amplified.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/auth
      # - name: Install amplify
      #   run: npm install amplify
      #   working-directory: amplify-js-samples-staging/samples/react/auth/react-amplified
      # # - name: Start application and run test
      # #   run: ../amplify-js/.circleci/retry-yarn-script.sh -s \
      # #       "ci:test \
      # #       react
      # #       auth
      # #       credentials-auth
      # #       credentials-auth
      # #       ${{ matrix.BROWSER }} \
      # #       dev \
      # #       ${{ inputs.amplifyjs_dir == true && env.AMPLIFY_DIR || ''}}" \
      # #       -n ${{ inputs.retry_count }}
      # #   working-directory: amplify-js-samples-staging
      # #   shell: bash
      
      # #Angular
      # - name: Install angular CLI
      #   run: npm install - g @angular/cli
      # - name: Create angular application
      #   run: npx -p @angular/cli ng new angular-app
      #   working-directory: amplify-js-samples-staging/samples/angular
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/angular/angular-app
      # - name: Copy src from samples staging repo
      #   run: |
      #     cp -R ./samples/angular/interactions/chatbot-component/src ./samples/angular/angular-app
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp chatbot-component.spec.js angular-app.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/interactions
      # - name: Install amplify
      #   run: npm install amplify
      #   working-directory: amplify-js-samples-staging/samples/angular/angular-app

      # #Next
      # - name: Create next application
      #   run: npx create-next-app next-amplified --no-app
      #   working-directory: amplify-js-samples-staging/samples/next/auth
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/next/auth/next-amplified
      # - name: Copy src from samples staging repo
      #   run: |
      #     cp -R ./samples/next/auth/auth-rsc/src ./samples/react/auth/next-amplified
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp auth-rsc.spec.js next-amplified.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/auth
      # - name: Install amplify
      #   run: npm install amplify
      #   working-directory: amplify-js-samples-staging/samples/next/auth/next-amplified
      
      #   #Javascript
      # - name: Create javascript application
      #   run: |
      #     mkdir -p javascript-amplified/src && cd javascript-amplified
      #     touch index.html src/app.js webpack.config.js
      #   working-directory: amplify-js-samples-staging/samples/javascript
      # - name: Install dependencies
      #   run: |
      #     npm install -g npm@latest
      #     npm install aws-amplify -legacy-peer-deps
      #   working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified
      # - name: Copy src from samples staging repo
      #   run: |
      #     cp -R ./samples/javascript/auth/auth-cdn/src ./samples/javascript/javascript-amplified
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp auth-cdn.spec.js javascript-amplified.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/auth
    
    
        #Vue
      - name: Create Vue application
        run: | 
          npm init vue@3
          printf vue-amplified
          printf No
          printf No
          printf No
          printf No
          printf No
          printf No
          printf No
        working-directory: amplify-js-samples-staging/samples/vue/auth
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified
      # - name: Copy src from samples staging repo
      #   run: |
      #     cp -R ./samples/javascript/auth/auth-cdn/src ./samples/javascript/javascript-amplified
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp auth-cdn.spec.js javascript-amplified.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/auth
      # - name: Install amplify
      #   run: npm install amplify
      #   working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified


    #     #Vue
    #   - name: Create vue application
    #     run: npm init vue@3
    #   - name: Copy App.vue from Samples Staging Repo
    #     run: |
    #       cp ./amplify-js-samples-staging/samples/vue/interactions/chatbot-component-vue3/src/App.vue ./vue-amplified/App.vue
    #   - name: Run application
    #     run: npm run dev
    #     working-directory: vue-amplified


