name: Prebuild AmplifyJsSamplesStaging

on:
  workflow_call:
    secrets:
      GH_TOKEN_AMPLIFY_JS_AUTOMATION:
        required: true
jobs:
  pre-staging:
    name: Prebuild Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js
      - name: Setup samples staging
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_AMPLIFY_JS_AUTOMATION: ${{ secrets.GH_TOKEN_AMPLIFY_JS_AUTOMATION }}
