name: 'Canary E2E Tests'

on:
  workflow_call:

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-macos:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-canary-e2e-runner.yml
  sample-app-tests:
    secrets: inherit
    uses: ./.github/workflows/callable-canary-sampleapp-tests.yml
  
  what-is-going-on:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I?
        run: |
          pwd
          ls
      - name: Where am I?
        run: |
          pwd
          ls
        working-directory: ./.github/actions/

  # log-failure-metric:
  #   # Send a failure data point to metric PublishNextFailure in github-workflows@ us-east-2, if it's a failure
  #   runs-on: ubuntu-latest
  #   #needs: build-test
  #   if: ${{ failure() }}
  #   steps:
  #     - name: Log failure data point to metric PublishNextFailure
  #       uses: ./.github/actions/log-metrics/action.yml
  #       with:
  #         metric-name: PublishNextFailure
  #         value: 1
  #         role-to-assume: ${{ secrets.METRIC_LOGGER_ROLE_ARN }} #what is this?
  #         aws-region: us-east-2
  log-success-metric:
    # Send a success data point to metric PublishNextFailure in github-workflows@ us-east-2, if it's a success
    runs-on: ubuntu-latest
    #needs: build-test do we need this?      
    if: ${{ success() }}
    steps:
      - name: Log success data point to metric PublishNextFailure
        uses: ./.github/actions/log-metrics/action.yml #cannot find this??
        with:
          metric-name: PublishNextFailure
          value: 0
          role-to-assume: ${{ secrets.METRIC_LOGGER_ROLE_ARN }} #what is this?
          aws-region: us-east-2