name: 'Canary Sample App Tests'

on:
  workflow_call:

env:      
  NPM_REGISTRY: http://localhost:4873/
  NPM_USER: circleci
  NPM_PASS: circleci
  NPM_EMAIL: circleci@amplify.js
  AMPLIFY_DIR: /home/runner/work/amplify-js/amplify-js/amplify-js
  CYPRESS_GOOGLE_CLIENTID: ${{ secrets.CYPRESS_GOOGLE_CLIENTID }}
  CYPRESS_GOOGLE_CLIENT_SECRET: ${{ secrets.CYPRESS_GOOGLE_CLIENT_SECRET }}
  CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.CYPRESS_GOOGLE_REFRESH_TOKEN }}

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        BROWSER: [chrome]

    steps: 
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js  
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}
      - name: Setup node and build the repository
        uses: stocaaro/amplify-js/.github/actions/node-and-build@main

        #React
      - name: Create react application
        run: npx create-react-app react-amplified
        working-directory: amplify-js-samples-staging/samples/react/auth
      - name: Remove existing src folder
        run: rm -rf src
        working-directory: amplify-js-samples-staging/samples/react/auth/react-amplified
        #copy the json over as well
      - name: Copy src and json from samples staging repo
        run: |
          cp -R ./samples/react/auth/credentials-auth/src ./samples/react/auth/react-amplified
          cp ./samples/react/auth/credentials-auth/package.json ./samples/react/auth/react-amplified/package.json
        working-directory: amplify-js-samples-staging
      - name: Copy test file from samples staging repo
        run: |
          cp credentials-auth.spec.js react-amplified.spec.js
        working-directory: amplify-js-samples-staging/cypress/integration/auth
      - name: Install amplify
        run: npm install amplify
        working-directory: amplify-js-samples-staging/samples/react/auth/react-amplified
      - name: Start application and run test
        run: |
            ../amplify-js/.circleci/retry-yarn-script.sh -s \
            "ci:test \
            react \
            auth \
            react-amplified \
            react-amplified \
            ${{ matrix.BROWSER }} \
            dev" \
            -n 3
        working-directory: amplify-js-samples-staging
        shell: bash
      
      #Angular
      - name: Install angular CLI
        run: npm install - g @angular/cli
      - name: Create angular application
        run: npx -p @angular/cli ng new angular-app
        working-directory: amplify-js-samples-staging/samples/angular
      - name: Remove existing src folder
        run: rm -rf src
        working-directory: amplify-js-samples-staging/samples/angular/angular-app
      - name: Copy src and json from samples staging repo
        run: |
          cp -R ./samples/angular/interactions/chatbot-component/src ./samples/angular/angular-app
          cp ./samples/angular/interactions/chatbot-component/package.json ./samples/angular/angular-app/package.json
        working-directory: amplify-js-samples-staging
      - name: Copy test file from samples staging repo
        run: |
          cp chatbot-component.spec.js angular-app.spec.js
        working-directory: amplify-js-samples-staging/cypress/integration/interactions
      - name: Install amplify
        run: |
          npm install -g npm@latest
          npm install aws-amplify -legacy-peer-deps
        working-directory: amplify-js-samples-staging/samples/angular/angular-app
      - name: Start application and run test
        run: |
            ../amplify-js/.circleci/retry-yarn-script.sh -s \
            "ci:test \
            angular \
            interactions \
            angular-app \
            angular-app \
            ${{ matrix.BROWSER }} \
            dev" \
            -n 3
        working-directory: amplify-js-samples-staging
        shell: bash

      #Next
      - name: Create next application
        run: npx create-next-app next-amplified --no-app
        working-directory: amplify-js-samples-staging/samples/next/auth
      - name: Remove existing src folder
        run: rm -rf src
        working-directory: amplify-js-samples-staging/samples/next/auth/next-amplified
      - name: Copy src and json from samples staging repo
        run: |
          cp -R ./samples/next/auth/auth-rsc/src ./samples/next/auth/next-amplified
          cp ./samples/next/auth/auth-rsc/package.json ./samples/next/auth/next-amplified/package.json
        working-directory: amplify-js-samples-staging
      - name: Copy test file from samples staging repo
        run: |
          cp auth-rsc.spec.js next-amplified.spec.js
        working-directory: amplify-js-samples-staging/cypress/integration/auth
      - name: Install amplify
        run: |
          npm install -g npm@latest
          npm install aws-amplify -legacy-peer-deps
        working-directory: amplify-js-samples-staging/samples/next/auth/next-amplified
      - name: Start application and run test
        run: |
            ../amplify-js/.circleci/retry-yarn-script.sh -s \
            "ci:test \
            next \
            auth \
            next-amplified \
            next-amplified \
            ${{ matrix.BROWSER }} \
            dev" \
            -n 3
        working-directory: amplify-js-samples-staging
        shell: bash
      
        #Javascript
      - name: Create javascript application
        run: |
          mkdir -p javascript-amplified/src && cd javascript-amplified
          touch index.html src/app.js webpack.config.js
        working-directory: amplify-js-samples-staging/samples/javascript
      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install aws-amplify -legacy-peer-deps
        working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified
      - name: Remove existing src folder
        run: rm -rf src
        working-directory: amplify-js-samples-staging/samples/javascript/javascript-amplified
      - name: Copy src and json from samples staging repo
        run: |
          cp -R ./samples/javascript/auth/auth-cdn/src ./samples/javascript/javascript-amplified
          cp ./samples/javascript/auth/auth-cdn/package.json ./samples/javascript/javascript-amplified/package.json
        working-directory: amplify-js-samples-staging
      - name: Copy test file from samples staging repo
        run: |
          cp auth-cdn.spec.js javascript-amplified.spec.js
        working-directory: amplify-js-samples-staging/cypress/integration/auth
      - name: Start application and run test
        run: |
            ../amplify-js/.circleci/retry-yarn-script.sh -s \
            "ci:test \
            javascript \
            auth \
            javascript-amplified \
            javascript-amplified \
            ${{ matrix.BROWSER }} \
            dev" \
            -n 3
        working-directory: amplify-js-samples-staging
        shell: bash
    
    
        #Vue
        #TODO: FIX
      # - name: Create Vue application
      #   run: | 
      #     npm init vue@3
      #   working-directory: amplify-js-samples-staging/samples/vue/auth
      # - name: Remove existing src folder
      #   run: rm -rf src
      #   working-directory: amplify-js-samples-staging/samples/vue/auth/vue-project
      # - name: Copy src and json from samples staging repo
      #   run: |
      #     cp -R ./samples/vue/auth/authenticator-vue3/src ./samples/vue/auth/vue-project
      #     cp ./samples/vue/auth/authenticator-vue3/package.json ./samples/vue/vue-project/package.json
      #   working-directory: amplify-js-samples-staging
      # - name: Copy test file from samples staging repo
      #   run: |
      #     cp authenticator-vue3.spec.js vue-project.spec.js
      #   working-directory: amplify-js-samples-staging/cypress/integration/auth
      # - name: Install amplify
      #   run: npm install amplify
      #   working-directory: amplify-js-samples-staging/samples/vue/auth/vue-project
      # - name: Start application and run test
      #   run: |
      #       ../amplify-js/.circleci/retry-yarn-script.sh -s \
      #       "ci:test \
      #       vue \
      #       auth \
      #       vue-project \
      #       vue-project \
      #       ${{ matrix.BROWSER }} \
      #       dev" \
      #       -n 3
      #   working-directory: amplify-js-samples-staging
      #   shell: bash



