name: 'Canary Sample App Tests'

on:
  workflow_call:

jobs:
  build_apps:
    name: Build Sample App Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        languages: ['react'] #missing Javascript, Next, Vue, Angular because all run differently

    steps: 
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js  
      - name: Setup samples staging repository
        uses: ./amplify-js/.github/actions/setup-samples-staging
        with:
          GH_TOKEN_STAGING_READ: ${{ secrets.GH_TOKEN_STAGING_READ }}

        #React
      - name: Create application
        run: npx create-${{ matrix.languages }}-app ${{ matrix.languages }}-amplified
      - name: Copy App.js from Samples Staging Repo
        run: |
          cp samples/${{ inputs.framework }}/auth/credentials-auth/src/App.js ${{ matrix.languages }}-amplified/App.js
        working-directory: amplify-js-samples-staging
      - name: Run application
        run: npm start
        working-directory: ${{ matrix.languages }}-amplified

