name: 'Prebuild AmplifyJs'

on:
  workflow_call:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Setup samples staging
        secrets: inherit
        uses: ./.github/actions/setup-samples-staging
