name: PR Validation

concurrency:
  group: pr-${{ github.event.pull_request.number }}-${{ github.event.sender.login }} # This is to make the group name unique for a PR.
  cancel-in-progress: true

on:
  pull_request:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          # Minimal depth 2 so we can checkout the commit before possible merge commit.
          fetch-depth: 2
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
        with:
          is-prebuild: true
  get-package-list:
    uses: ./.github/workflows/callable-get-package-list.yml
  unit-tests:
    needs:
      - prebuild
      - get-package-list
    strategy:
      matrix:
        package: ${{ fromJSON(needs.get-package-list.outputs.packages) }}
      fail-fast: false
    uses: ./.github/workflows/callable-unit-tests.yml
    with:
      package: ${{ matrix.package }}
  bundle-size-tests:
    needs: prebuild
    uses: ./.github/workflows/callable-bundle-size-tests.yml
  all-tests-pass:
    needs:
      - unit-tests
      - bundle-size-tests
    runs-on: ubuntu-latest
    steps:
      - name: All tests passed
        run: echo "All tests passed"
