name: Push - release from release to latest

on:
  push:
    branches:
      - release

jobs:
  release:
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-release.yml
  publish-docs:
    needs:
      - release
    secrets: inherit
    uses: ./.github/workflows/callable-docs-update.yml