name: Push - release from main to unstable

on:
  push:
    branches:
      - feat/github-actions/test-stocaaro

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-release-verification.yml
  unstable-release:
    needs:
      - e2e
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-preid.yml
    with:
      preid: unstable
