name: Push - run release verifications

concurrency:
  # group name unique for push to push-integ-test
  group: push-e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - feat/github-actions/main
      - feat/github-actions/test-stocaaro
      - feat/github-actions/test-ashwinkumar6
      - feat/github-actions/test-yingku

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-release-verification.yml
