name: Push - release from release to latest

concurrency:
  # group name unique for push to push-latest-release
  group: push-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    branches:
      - release

jobs:
  release:
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-release.yml
