name: 'Push - release for feature preid'

on:
  push:
    branches:
      # Change this to your branch name where "example-preid" corresponds to the preid you want your changes released on
      - feat/example-preid/main

jobs:
  e2e:
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-e2e.yml@main
  parse-preid:
    name: 'Parse preid from branch'
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
      - run: echo $BRANCH
      - id: output_preid
        run: echo "::set-output name=preid::${BRANCH##*/}"
    outputs:
      preid: ${{ steps.output_preid.outputs.packages }}

  preid-release:
    needs:
      - e2e
      - parse-preid
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-preid-release.yml@main
    # The preid should be detected from th branch name recommending feat/PREID/whatvever as branch naming pattern
    with:
      preid: ${{ needs.parse-preid.outputs.preid }}
