on:
  push:
    branches: []

jobs:
  e2e:
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-e2e.yml@main
  preid-release:
    needs:
      - e2e
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-preid-release.yml@main
    # The preid should be detected from th branch name recommending feat/PREID/whatvever as branch naming pattern
    with:
      preid: TODO-detect
