name: 'Push - release from main to unstable'

on:
  push:
    branches:
      - main

jobs:
  e2e:
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-e2e@main
  unstable-release:
    needs:
      - e2e
    secrets: inherit
    uses: stocaaro/amplify-js/.github/workflows/callable-preid-release@main
    with:
      preid: unstable
