name: 'Push - release from release to latest'

on:
  push:
    branches:
      - release

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-e2e.yml
  release:
    needs:
      - e2e
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-release.yml
