name: 'Push - release from main to unstable'

on:
  push:
    branches:
      - main

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-e2e.yml
  unstable-release:
    needs:
      - e2e
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-preid.yml
    with:
      preid: unstable
