name: Set Node and Build
description: Checks out Amplify and builds the package

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 16
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: 16
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Install
      run: |
        mv .yarnrc ._yarnrc
        yarn
      shell: bash
    - name: Bootstrap
      run: yarn bootstrap
      shell: bash
    - uses: actions/cache@v2
      id: cache-build-artifacts
      with:
        path: |
          **/dist
          **/lib
          **/
          **/lib-esm/
          **/es/
          **/esm/
          **/cjs/
        key: ${{ runner.os }}-build-artifacts-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
    - name: Build packages
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
