name: Set Node and Build
description: Checks out Amplify and builds the package
inputs:
  is-prebuild:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 16
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: 16
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: cache-yarn-artifacts
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-artifacts-${{ hashFiles('./amplify-js/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-artifacts-
    - name: Install
      if: steps.cache-yarn-artifacts.outputs.cache-hit != 'true'
      run: yarn
      shell: bash
      working-directory: ./amplify-js
    - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: cache-build-artifacts
      with:
        path: |
          **/dist
          **/lib
          **/lib-esm/
          **/es/
          **/esm/
          **/cjs/
          **/packages/core/src/Platform/version.ts
        key: ${{ runner.os }}-build-artifacts-${{ hashFiles('./amplify-js/packages/*/src/**', './amplify-js/packages/*/*.json', './amplify-js/packages/*/*.js') }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Bootstrap
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn bootstrap
      shell: bash
      working-directory: ./amplify-js
    - name: Build packages
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
      working-directory: ./amplify-js
