name: Set Node and Build
description: Checks out Amplify and builds the package

runs:
  using: 'composite'
  steps:
    - name: Where we at?
      run: |
        pwd
        ls
      shell: bash
    - name: Where we at?
      run: |
        pwd
        ls
      shell: bash
      working-directory: ./aws-amplify
    - name: Create cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1 https://github.com/actions/cache/commit/88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      id: cache-js-build
      with:
        key: aws-amplify-js-build-${{ github.sha }}
        path: ./aws-amplify
    - name: Setup Node.js 16
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0 https://github.com/actions/setup-node/commit/64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: 16
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    - name: Install
      run: |
        mv .yarnrc ._yarnrc
        yarn
      shell: bash
      working-directory: ./aws-amplify
    - name: Bootstrap
      run: yarn bootstrap
      shell: bash
      working-directory: ./aws-amplify
    - uses: actions/cache@v2
      id: cache-build-artifacts
      with:
        path: |
          ./aws-amplify/**/dist
          ./aws-amplify/**/lib
          ./aws-amplify/**/
          ./aws-amplify/**/lib-esm/
          ./aws-amplify/**/es/
          ./aws-amplify/**/esm/
          ./aws-amplify/**/cjs/
        key: ${{ runner.os }}-build-artifacts-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-artifacts-
    - name: Build packages
      if: steps.cache-build-artifacts.outputs.cache-hit != 'true'
      run: yarn build
      shell: bash
      working-directory: ./aws-amplify
